WebBanHang_2180604857/Models/ShoppingCart.cs
using WebBanHang_2180604857.Models;

namespace WebBanHang_2180604857.Models
{
    public class ShoppingCart
    {
        public List<CartItem> Items { get; set; } = new List<CartItem>();
        public void AddItem(CartItem item)
        {
            var existingItem = Items.FirstOrDefault(i => i.ProductId ==
            item.ProductId);
            if (existingItem != null)
            {
                existingItem.Quantity += item.Quantity;
            }
            else
            {
                Items.Add(item);
            }
        }
        public void RemoveItem(int productId)
        {
            var itemToRemove = Items.FirstOrDefault(i => i.ProductId == productId);
            if (itemToRemove != null)
            {
                Items.Remove(itemToRemove);
            }
        }
        public void UpdateQuantity(int productId, int quantity)
        {
            var itemToUpdate = Items.FirstOrDefault(i => i.ProductId == productId);
            if (itemToUpdate != null)
            {
                itemToUpdate.Quantity = quantity;
            }
        }
        // Các phương thức khác...
    }
}

WebBanHang_2180604857/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebBanHang_2180604857.DataAccess;
using WebBanHang_2180604857.Helpers;
using WebBanHang_2180604857.Models;
using WebBanHang_2180604857.Repositories;

namespace WebBanHang_2180604857.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IProductRepository _productRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingCartController(IProductRepository productRepository,UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _productRepository = productRepository;
            _db = context;     
        }
        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
            Product product = await GetProductFromDatabaseAsync(productId);
            var cartItem = new CartItem 
            {
                ProductId = productId,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity
            };
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            cart.AddItem(cartItem);
            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index");
        }
//Function Update,Remove,RemoveAll----------------------------------------------------------------------------------
        [HttpPost]
        public IActionResult UpdateCartItem(int productId, int quantity)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart != null)
            {
                var cartItem = cart.Items.FirstOrDefault(i => i.ProductId == productId);
                if (cartItem != null)
                {
                    // Cập nhật số lượng và giá tiền
                    cartItem.Quantity = quantity;
                    cartItem.Price = cartItem.Price;

                    // Lưu lại giỏ hàng vào Session sau khi cập nhật
                    HttpContext.Session.SetObjectAsJson("Cart", cart);

                    return RedirectToAction("Index");
                }
            }

            return Json(new { success = false, message = "Product not found in cart" });
        }
        [HttpPost]
        public IActionResult RemoveFromCart(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart != null)
            {
                var cartItem = cart.Items.FirstOrDefault(i => i.ProductId == productId);
                if (cartItem != null)
                {
                    cart.Items.Remove(cartItem); // Remove the item from the cart
                    HttpContext.Session.SetObjectAsJson("Cart", cart); // Update the cart in session
                    return RedirectToAction("Index"); // Redirect to the cart page
                }
            }

            return Json(new { success = false, message = "Product not found in cart" });
        }
        [HttpPost]
        public IActionResult ClearAll()
        {
            HttpContext.Session.Remove("Cart"); // Remove the entire cart from the session
            return RedirectToAction("Index"); // Redirect to the cart page
        }
//------------------------------------------------------------------------------------------------------
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            return View(cart);
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Order());
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var cart =
            HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart == null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            var user = await _userManager.GetUserAsync(User);
            order.UserId = user.Id;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();
            //Luu đơn hàng và chi tiết đơn hàng 
            _db.Orders.Add(order);
            await _db.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order.Id); // Trang xác nhận hoàn thành đơn hàng
    }


        // Các actions khác...
        private async Task<Product> GetProductFromDatabaseAsync(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            return await _productRepository.GetByIdAsync(productId);
        }
    }
}

WebBanHang_2180604857/Views/ShoppingCart/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        h2 {
            text-align: center;
            color: #343a40;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }

        th {
            background-color: #007bff;
            color: white;
        }

        .btn {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .btn-primary {
            background-color: #007bff;
            color: white;
        }

        .btn-danger {
            background-color: #dc3545;
            color: white;
        }

        .btn-success {
            background-color: #28a745;
            color: white;
        }

        .btn:hover {
            background-color: #0056b3;
        }

        .alert {
            margin-top: 20px;
            padding: 15px;
            border-radius: 5px;
            color: #0c5460;
            background-color: #d1ecf1;
            border: 1px solid #bee5eb;
        }

        .alert-heading {
            margin-top: 0;
        }

        .text-center {
            text-align: center;
        }

        img {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<link href="~/css/checkout.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
@model Order
<div class="container mt-5">
    <h1 class="text-center mb-4">Nhập thông tin đặt hàng</h1>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="card-title">Thanh Toán</h2>
                </div>
                <div class="card-body">
                    <form asp-action="Checkout" method="post">
                        <div class="form-group">
                            <label asp-for="ShippingAddress">Nhập địa chỉ đặt hàng</label>
                            <input asp-for="ShippingAddress" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Notes">Ghi Chú</label>
                            <textarea asp-for="Notes" class="form-control" rows="4"></textarea>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a class="btn btn-secondary btn-lg" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Trở về</a>
                            <button type="submit" class="btn btn-success btn-lg">Đặt hàng</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="item active">
    <div class="col-sm-12">
        <h1 style="text-align: center;">Thanh toán nhanh gọn! Gửi hàng nhanh chóng :3</h1>
        <img src="https://static.vecteezy.com/system/resources/previews/000/702/086/original/shopping-online-on-website-vector.jpg" width="100%" />
    </div>
</div>

WebBanHang_2180604857/Views/ShoppingCart/Index.cshtml
@{
    Layout = null;
}
@model ShoppingCart

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        h2 {
            text-align: center;
            color: #343a40;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }

        th {
            background-color: #007bff;
            color: white;
        }

        .btn {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .btn-primary {
            background-color: #007bff;
            color: white;
        }

        .btn-danger {
            background-color: #dc3545;
            color: white;
        }

        .btn-success {
            background-color: #28a745;
            color: white;
        }

        .btn:hover {
            background-color: #0056b3;
        }

        .alert {
            margin-top: 20px;
            padding: 15px;
            border-radius: 5px;
            color: #0c5460;
            background-color: #d1ecf1;
            border: 1px solid #bee5eb;
        }

        .alert-heading {
            margin-top: 0;
        }

        .text-center {
            text-align: center;
        }

        img {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<div class="container mt-5">
    <h2 class="mb-4">Thông tin mua sắm </h2>

    @if (Model.Items.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Price</td>
                        <td>
                            <form asp-controller="ShoppingCart" asp-action="UpdateCartItem" method="post">
                                <input type="hidden" name="productId" value="@item.ProductId" />
                                <input type="number" name="quantity" id="quantity_@item.ProductId" value="@item.Quantity" min="1" class="form-control" style="width: 80px;" />
                                <button class="btn btn-primary btn-sm mt-2" type="submit">Update</button>
                            </form>
                        </td>
                        <td>@(item.Price * item.Quantity)</td>
                        <td>
                            <form asp-action="RemoveFromCart" asp-route-productId="@item.ProductId" method="post">
                                <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <form asp-action="ClearAll" method="post">
            <button type="submit" class="btn btn-danger">Clear All</button>
        </form>


        <div class="text-center">
            <a class="btn btn-info btn-lg mr-3" asp-area="" asp-controller="Home" asp-action="Index">Tiếp tục mua sắm</a>
            <a class="btn btn-success btn-lg" asp-area="" asp-controller="ShoppingCart" asp-action="Checkout">Thanh Toán</a>
        </div>
    }
    else
    {
        <div class="alert alert-info text-center" role="alert">
            <h4 class="alert-heading">Giỏ hàng của bạn đang trống.</h4>
            <hr>
            <p class="mb-0">Bạn chưa thêm bất kỳ sản phẩm nào vào giỏ hàng.</p>
            <button onclick="window.location.href='@Url.Action("Index", "Home")'" class="btn btn-primary mt-3">Bắt đầu mua sắm ngay!</button>
        </div>
    }

</div>

<div class="item active">
    <div class="col-sm-12">
        <h1 style="text-align: center;">Chào mừng đến với cửa hàng của chúng tôi!</h1>
        <img src="https://static.vecteezy.com/system/resources/previews/000/702/086/original/shopping-online-on-website-vector.jpg" width="100%" />
    </div>
</div>

WebBanHang_2180604857/Views/ShoppingCart/OrderCompleted.cshtml
@{
    Layout = null;
}
@model int;
<!DOCTYPE html>
<html>
<head>
    <title>Order Completed</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        /* Custom styles for order completed form */
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
        }

        .order-completed-container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #dee2e6;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h1, h2 {
            color: #007bff;
        }

        .btn-custom {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="order-completed-container">
        <h1>Chúc mừng bạn đã thanh toán thành công</h1>
        <h2>Mã đơn hàng của bạn là @Model</h2>
        <a class="btn btn-primary btn-custom" href="@Url.Action("Index", "Home")">Trở về trang chủ</a>
    </div>
</body>
</html>